FROM public.ecr.aws/lambda/nodejs:20

# Copy final outputs after build to the lambda task root
COPY ./dist ${LAMBDA_TASK_ROOT}

COPY ./package.json ${LAMBDA_TASK_ROOT}
COPY ./package-lock.json ${LAMBDA_TASK_ROOT}

RUN npm clean-install --no-audit --no-fund --progress=false --omit dev


CMD ["lambda.js"]
