FROM public.ecr.aws/lambda/python:3.11

COPY ./src ${LAMBDA_TASK_ROOT}

# COPY .//requirements.txt ./requirements.txt

# RUN pip install psycopg2-binary
# RUN apk add postgresql-dev gcc python3-dev musl-dev

RUN yum install --quiet -y gcc python3-devel postgresql-devel git make awk procps-ng
RUN pip install psycopg2-binary
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt --target "${LAMBDA_TASK_ROOT}"

CMD ["app.handler"]
