name: "Run pyright"
on:
  push:
    branches:
      - dev
      - master
  # pull_request:
  #     - master
  #     - dev

jobs:
  Pyright:
    name: Detect type errors with Pyright
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: echo $(cat .python-version)

      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pipenv install

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Execute pyright
        uses: jakebailey/pyright-action@v2
